# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: CleverTwain
# Generated on: 6/7/2018

@{
    RootModule        = 'CT.GetNthWeekDay.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = 'f3f0e7fb-2d64-44e8-b8a9-9f28ecd93edc'
    Author            = 'CleverTwain'
    CompanyName       = 'Unknown'
    Copyright         = '(c) CleverTwain. All rights reserved.'
    Description       = ''
    FunctionsToExport = @('Get-NthWeekday')
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}
